# Types of Presence:
# Type 0 = PLAYING
# Type 1 = STREAMING
# Type 2 = LISTENING
# Type 3 = WATCHING

Valid = [
    { type = 0, title = "Mondegreen" },
    { type = 0, title = "Cards Against Humanity" },
    { type = 2, title = "Childish Gambino" },
    { type = 0, title = "with Medusa" },
    { type = 2, title = "the Siren's song" }
]