[English]
    [Error]    
        STANDARD        = "Shoot! There was an error trying to execute that command! Please try again momentarily."
        INVALID_COMMAND = "Sorry, that command was invalid."
        GUILD_ONLY      = "Please try executing this command inside of a server/guild."
        DISABLED        = "That command is either non-existent or it is (globally) disabled. Please try again later."

    Unique = [
        
    ]